spring:
  application:
    name: pic

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/picpaydb
    username: admin
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
